"""add signin & gold_coin related column in User

Revision ID: a66fa0727e09
Revises: None
Create Date: 2017-02-23 10:02:36.794212

"""

# revision identifiers, used by Alembic.
revision = 'a66fa0727e09'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gold_coin', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('signin_num', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('signin_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'signin_time')
    op.drop_column('users', 'signin_num')
    op.drop_column('users', 'gold_coin')
    ### end Alembic commands ###
